FROM centos:centos7
MAINTAINER Pavel Sviderski <pavel@psviderski.name>

RUN yum install -y http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm \
 && yum install -y python34u \
 && yum clean all
